In [1]:
import cv2
import os
import numpy as np

In [60]:

def as_parallel_as_possible(curve, points):
    n = len(curve)
    I = np.eye(2*n)
    P = []
    for point in curve:
        P.append(-point[0])
        P.append(-point[1])
    P = np.array(P).reshape((2*n, 1))
    M = []
    M.append(points[1][0] - points[0][0])
    M.append(points[1][1] - points[0][1])
    M = np.array(M).reshape((2, 1))
    A = []
    A.append([(i+1)%2 for i in range(2*n)])
    A.append([i%2 for i in range(2*n)])
    A = np.array(A)
    print(I, np.transpose(A), P, M, sep='\n')
    X = (-I + np.transpose(A) @ A / n) @ P + np.transpose(A) @ M / n
    result = []
    for i in range(n):
        result.append([X[2*i].item(), X[2*i+1].item()])
    diff = [points[0][0] - result[0][0] , points[0][1] - result[0][1]]
    print(len(result))
    for i in range(len(result)):
        result[i] = [result[i][0] + diff[0], result[i][1] + diff[1]]
    return result

In [50]:
curve = [
    [100, 100],
    [200, 200],
    [200, 300],
]
points = [
    [125, 70],
    [300, 300]
]

In [61]:
size = (500, 500)

image = np.zeros(size, dtype=np.int8)

for i in range(len(curve) - 1):
    cv2.line(image, curve[i], curve[i+1], (255, 0, 0), 3)

res = as_parallel_as_possible(curve, points)
print(res)
for i in range(len(res) - 1):
    print([int(a) for a in res[i]])
    cv2.line(image, [int(a) for a in res[i]] , [int(a) for a in res[i + 1]], (255, 0, 0), 3)
    # cv2.line(image, res[i] , res[i + 1], (255, 0, 0), 3)

cv2.imshow('Image with Lines', image)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
[[1 0]
 [0 1]
 [1 0]
 [0 1]
 [1 0]
 [0 1]]
[[-100]
 [-100]
 [-200]
 [-200]
 [-200]
 [-300]]
[[175]
 [230]]
3
[[125.0, 70.0], [225.0, 170.0], [225.0, 270.0]]
[125, 70]
[225, 170]
